"""initial schema

Revision ID: 0964b8fff254
Revises: 
Create Date: 2026-06-03 23:54:29.524466
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0964b8fff254'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('confederation', sa.String(length=20), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('fifa_rank', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Float(), nullable=False),
    sa.Column('defence', sa.Float(), nullable=False),
    sa.Column('chemistry', sa.Float(), nullable=False),
    sa.Column('coach_quality', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('elo_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('opponent', sa.String(length=120), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elo_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elo_history_team_id'), ['team_id'], unique=False)
        batch_op.create_index('ix_elo_history_team_time', ['team_id', 'recorded_at'], unique=False)

    op.create_table('saved_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_scenarios_owner_id'), ['owner_id'], unique=False)

    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('match', 'tournament', 'monte_carlo', name='simkind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='simstatus'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulations_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_simulations_status'), ['status'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('runs_completed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_simulation_id'), ['simulation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_simulation_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulations_status'))
        batch_op.drop_index(batch_op.f('ix_simulations_public_token'))
        batch_op.drop_index(batch_op.f('ix_simulations_owner_id'))
        batch_op.drop_index(batch_op.f('ix_simulations_created_at'))

    op.drop_table('simulations')
    with op.batch_alter_table('saved_scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_scenarios_owner_id'))

    op.drop_table('saved_scenarios')
    with op.batch_alter_table('elo_history', schema=None) as batch_op:
        batch_op.drop_index('ix_elo_history_team_time')
        batch_op.drop_index(batch_op.f('ix_elo_history_team_id'))

    op.drop_table('elo_history')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_code'))

    op.drop_table('teams')
    # ### end Alembic commands ###
